/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.so.agi.ilivalidator.ext;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
